repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # You can check for the latest version on GitHub
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
